### ISSUE TITLE
请教您一些超表面全息的问题

### ISSUE THREAD

**Issue by DonaldJefferson** [XuRuLin/HoloLib_MATLAB#8]
您好
我下载了您的代码，发现超表面全息图的代码缺少了一个“F16.bmp”文件。然后我使用其他的图片代替，生成了超表面，但是我并不知道这种类型超表面的响应属性。请问有相关的文献吗，还有“F16.bmp”文件有什么要求吗？
谢谢您

**Comment by XuRulin** [comment]
**感谢你的提问。**
1、F16.bmp是我自己测试使用的一个图片文件，我的疏忽导致忘记修改回来，之后我会替换为image中的图片文件。
2、生成的mdat文件本质是一个记录全息图相位索引的文本文件，与具体的超表面无关。你可以用mdat文件在电磁学仿真软件生成相应的结构（我用的是FDTD Solutions，相关的生成脚本你可以在XuRuLin/FSMH_Library中找到）。
3、我自己的论文还在撰写，你可以参考一些他人论文[链接](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CDFD&dbname=CDFDLAST2019&filename=1018828896.nh&v=AoDJAKzV8tCkiYwi%25mmd2FTrKNQ1HvNKDOTQmK8%25mmd2BKXMtC0rW8BgcngYOJOSdV7Xw%25mmd2Fo%25mmd2BG0)。
4、我没有测试很多的图片类型，但是经验告诉我，最好选择灰度（8-bit）的BMP的图像，同时最好不要太大，否则在电磁学仿真软件中生成模型会花很长时间。

**Comment by DonaldJefferson** [comment]
好的，您的代码运行起来效果很好，谢谢您
